<h4>
<?php echo $this->__('Module List') ?>
</h4>
  
<?php   
        /*
        This will load one record from your database table.
        load(<module>_id) will load whatever ID number you give it.
        */
    /*
    $news = Mage::getModel('<module>/<module>')->load(1);
    echo $news->get<Module>Id();
    echo $news->getTitle();
    echo $news->getContent();
    echo $news->getStatus();
    */
  
        /*
        This block of code loads all of the records in the database table.
        It will iterate through the collection and the first thing it will do
        is set the Title to the current value of $i which is incremented each
        iteration and then echo that value back out.  At the very end it will
        save the entire collection.
        */
    /*
    $i = 0;
          
    $collection = Mage::getModel('<module>/<module>')->getCollection();
    $collection->setPageSize(5);
    $collection->setCurPage(2);
    $size = $collection->getSize();
    $cnt = count($collection);
    foreach ($collection as $item) {
        $i = $i+1;
        $item->setTitle($i);
        echo $item->getTitle();
    }
  
    $collection->walk('save');   
    */
  
        /*
        This shows how to load one value, change something and save it.
        */
  
    /*
    $object = Mage::getModel('<module>/<module>')->load(1);
    $object->setTitle('This is a changed title');
    $object->save();
    */
?>
<!--
  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/popbox/customStyle.css'); ?>">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/popbox/jquery-ui.css'); ?>">
  <script src="<?php echo $this->getSkinUrl('js/popbox/javascript.js'); ?>"></script>
  <script src="<?php echo $this->getSkinUrl('js/popbox/jquery-ui.js'); ?>"></script>

 <!--<div class="pupup-custom-popbox-container" >
    <div onblur="popboxClear()" class="pupup-custom-popbox" id="popbox-container">-->
 
<!--     <img class="pupup-logo" src="<?php echo $this->getSkinUrl('images/popbox/logo.png'); ?>">
      <span class="pupup-welcome"> Welcome to the BabyPlanet Family</span>
      <span class="pupup-cancel"  onclick="popboxClear()" id="popbox-cancel">x</span>
      <hr width="90%" class="pupup-hrr" />
      <div class="pupup-left-side">
        <h1 class="pupup-offer-title" >Why Sign up?</h1>
        <div class="pupup-offers">
          <h3 class="pupup-offer" >1. Get 10% discount coupon to start shopping</h3>
          <h3 class="pupup-offer" >2. Stay updated with new arrivals, deals and discount offers</h3>
          <h3 class="pupup-offer" >3. Get Personalized recomendations based on Baby's details</h3>
          <h3 class="pupup-offer" >& much more</h3>
        </div>
      </div>
      <div class="pupup-mid-side">
        <img src="<?php echo $this->getSkinUrl('images/popbox/line.png'); ?>" class="pupup-mid-side">
      </div>
      <div class="pupup-right-side"> 
        <input type="text" placeholder="Name" class="pupup-field name" />   
        <input type="text" placeholder="Email Address" class="pupup-field email" />
        <input type="text" placeholder="Child's Name" class="pupup-field child" />
        <h3 class="pupup-offer-dob" > &nbsp Child's DOB </h3>
        <input type="date"  placeholder="YYYY-MM-DD" min="2000-01-01" max="2015-12-31" class="pupup-field pupup-field-dob dob">
        <!--<input type="text" placeholder="Child's DOB" class="pupup-field pupup-field-dob dob" id="datepicker" />-->

<!--        <span> <img src="<?php echo $this->getSkinUrl('images/popbox/calender.png'); ?>" class="pupup-calender" /> </span>
          <ul class="pupup-gender">
            <li class="pupup-li-style pupup-boy">Boy</li>
            <li class="pupup-li-style pupup-girl">Girl</li>
          </ul>
        <input type="text" placeholder="Phone (optional)" class="pupup-field phone" />
        <input type="button" class="pupup-submit" value="Sign Up" >
      </div>
-->
